name: Cypress Tests w/ Allure Reporting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-tests:
    runs-on: ubuntu-22.04
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run Cypress Tests 🧪
        uses: cypress-io/github-action@v6

      - name: Generate Allure report
        run: npm run allure:generate

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
